## Define the two arguments that the 'template' expects
AS_JARS := \
AckR.jar         FibSLR.jar     Nim.jar         Test1.jar   Test6.jar \
BTreeR.jar       HanR.jar       Power.jar       Test10.jar  Test8.jar \
BubbleSortR.jar  Matrix.jar     Recursions.jar  Test12.jar  TicTacToe.jar \
FactSLR.jar      MergeSort.jar  Sudoku.jar      Test4.jar   WorkingSignals.jar

## Include the template, with it's standard clean rules and such
include ../Makefile.JavaTemplate
