## Define the two arguments that the 'template' expects
AS_JARS := \
Ackermann.jar         Double3.jar      List.jar               TestJulia6.jar \
BTree.jar             FactSum.jar      ListInt.jar            TestJulia7.jar \
BinarySearchTree.jar  FactSumList.jar  Makefile               Virtual.jar \
Domino.jar            Factorial.jar    MysteriousProgram.jar  \
Double.jar            Hanoi.jar        PartitionList.jar      \
Double2.jar           JARSONLY         Queen.jar  

## Include the template, with it's standard clean rules and such
include ../Makefile.JavaTemplate
