## Define the two arguments that the 'template' expects
AS_JARS := \
Break.jar                  Exc4.jar        TestJulia2.jar \
BubbleSort.jar             Exc5.jar        TestJulia3.jar \
Continue.jar               Init.jar        TestJulia4.jar \
Continue1.jar              KnapsackDP.jar  TestJulia5.jar \
CyclicalListDuplicate.jar  LinkedList.jar  costa09-example_1.jar \
Diff.jar                   Loop1.jar       costa09-example_2.jar \
Exc.jar                    Nested.jar      costa09-example_3.jar \
Exc1.jar                   Sequence.jar    costa09-example_4.jar \
Exc2.jar                   Sharing.jar     costa09-example_5.jar \
Exc3.jar                   TestJulia1.jar \

## Include the template, with it's standard clean rules and such
include ../Makefile.JavaTemplate
