## Define the two arguments that the 'template' expects
AS_JARS := \
AProVEMath.jar       ListContent.jar           PastaA5.jar   PastaB6.jar \
Collatz.jar          ListContentArbitrary.jar  PastaA6.jar   PastaB7.jar \
Convert.jar          ListContentTail.jar       PastaA7.jar   PastaB8.jar \
Count.jar            ListDuplicate.jar         PastaA8.jar   PastaC1.jar \
CountMetaList.jar    Log.jar                   PastaA9.jar   PastaC10.jar \
CountUpRound.jar     LogAG.jar                 PastaB1.jar   PastaC11.jar \
DivMinus.jar         LogBuiltIn.jar            PastaB10.jar  PastaC2.jar \
DivMinus2.jar        LogIterative.jar          PastaB11.jar  PastaC3.jar \
DivWithoutMinus.jar  LogMult.jar               PastaB12.jar  PastaC5.jar \
Duplicate.jar        McCarthyIterative.jar     PastaB13.jar  PastaC7.jar \
DuplicateNodes.jar   MinusBuiltIn.jar          PastaB14.jar  PastaC9.jar \
Flatten.jar          MinusMin.jar              PastaB15.jar  PlusSwap.jar \
FlattenTree.jar      MinusUserDefined.jar      PastaB16.jar  Round3.jar \
GCD.jar           MirrorTree.jar            PastaB17.jar  RunningPointers.jar \
GCD2.jar             Mod.jar                   PastaB18.jar  Samefringe.jar \
GCD3.jar             Overflow.jar              PastaB2.jar   Shuffle.jar \
GCD4.jar             PastaA1.jar               PastaB3.jar   SortCount.jar \
GCD5.jar             PastaA10.jar              PastaB4.jar   StupidArray.jar \
LessLeaves.jar       PastaA4.jar               PastaB5.jar   Take.jar

## Include the template, with it's standard clean rules and such
include ../Makefile.JavaTemplate
