## Define the two arguments that the 'template' expects
AS_JARS := \
Carre.jar          Iterations.jar   RSA.jar          Test3.jar  TriTas.jar \
Gauss.jar          JARSONLY         Test11.jar       Test5.jar  \
Graph.jar          Makefile         Test13Loops.jar  Test7.jar  \
Infix2Postfix.jar  NonPeriodic.jar  Test2.jar        Test9.jar

## Include the template, with it's standard clean rules and such
include ../Makefile.JavaTemplate
