## Define the two arguments that the 'template' expects
AS_JARS := AG313.jar CyclicPair2.jar        IntPath2.jar    SharingPair.jar \
	   ArrayClasses.jar DuplicateTreePath.jar IntRTA.jar TypeSwitch.jar \
           CyclicList.jar FlattenRTA.jar NestedLoop.jar CyclicPair.jar \
	   IntPath.jar NullPair.jar

## Include the template, with it's standard clean rules and such
include ../Makefile.JavaTemplate
